trigger:
  branch:
    - develop

kind: pipeline
type: docker
name: android

platform:
  os: linux

steps:
  - name: restore-cache-with-filesystem
    image: meltwater/drone-cache:dev
    pull: "if-not-exists"
    settings:
      backend: "filesystem"
      restore: true
      cache_key: 'yarn-{{ checksum "yarn.lock" }}'
      archive_format: "gzip"
      # filesystem_cache_root: "/tmp/cache "
      mount:
        - "node_modules"
    volumes:
      - name: cache
        path: /tmp/cache
  - name: do the deed
    image: webratio/nodejs-with-android-sdk:12.13.1
    commands:
      - npm install -g yarn
      - yarn
      - yarn cache dir
  - name: rebuild-cache-with-filesystem
    image: meltwater/drone-cache:dev
    pull: "if-not-exists"
    settings:
      backend: "filesystem"
      rebuild: true
      cache_key: 'yarn-{{ checksum "yarn.lock" }}'
      archive_format: "gzip"
      # filesystem_cache_root: "/tmp/cache"
      mount:
        - "node_modules"
    volumes:
      - name: cache
        path: /tmp/cache

volumes:
  - name: cache
    host:
      path: /tmp/cache
