trigger:
  branch:
    - develop

# ---
# kind: pipeline
# type: exec
# name: ios

# platform:
#   os: darwin

# steps:
#   # - name: yarn
#   #   commands:
#   #     - export HOME=/Users/powerminion
#   #     - export HOMEPATH=/Users/powerminion
#   #     - yarn
#   - name: do the deed
#     commands:
#       - export HOME=/Users/powerminion
#       - export HOMEPATH=/Users/powerminion
#       - yarn webrtc:setup
#       - npx rnv export -p ios -s appstore -c selectorcanary --ci
# node:
#   runner: powerminion

# depends_on:
#   - yarncache
# ---
kind: pipeline
type: docker
name: android

platform:
  os: linux

steps:
  - name: restore-cache-with-filesystem
    image: meltwater/drone-cache:dev
    pull: "if-not-exists"
    settings:
      backend: "filesystem"
      restore: true
      cache_key: 'yarn-{{ checksum "go.mod" }}'
      archive_format: "gzip"
      # filesystem_cache_root: "/tmp/cache"
      mount:
        - "vendor"
    volumes:
      - name: cache
        path: /tmp/cache
  - name: do the deed
    image: webratio/nodejs-with-android-sdk:12.13.1
    commands:
      - npm install -g yarn
      - yarn
  - name: rebuild-cache-with-filesystem
    image: meltwater/drone-cache:dev
    pull: "if-not-exists"
    settings:
      backend: "filesystem"
      rebuild: true
      cache_key: 'yarn-{{ checksum "go.mod" }}'
      archive_format: "gzip"
      # filesystem_cache_root: "/tmp/cache"
      mount:
        - "vendor"
    volumes:
      - name: cache
        path: /tmp/cache

volumes:
  - name: cache
    host:
      path: /tmp/cache
# ---
# kind: pipeline
# type: exec
# name: web

# platform:
#   os: darwin

# steps:
#   # - name: yarn
#   #   commands:
#   #     - export HOME=/Users/powerminion
#   #     - export HOMEPATH=/Users/powerminion
#   #     - yarn
#   - name: do the deed
#     commands:
#       - export HOME=/Users/powerminion
#       - export HOMEPATH=/Users/powerminion
#       - npx rnv export -p web -c selector --ci
# node:
#   runner: powerminion

# depends_on:
#   - yarncache
# ---
# kind: pipeline
# type: exec
# name: androidtv

# platform:
#   os: darwin

# steps:
#   # - name: yarn
#   #   commands:
#   #     - export HOME=/Users/powerminion
#   #     - export HOMEPATH=/Users/powerminion
#   #     - yarn
#   - name: do the deed
#     commands:
#       - export HOME=/Users/powerminion
#       - export HOMEPATH=/Users/powerminion
#       - npx rnv export -p androidtv -s playstore -c selectorcanary --ci
# node:
#   runner: powerminion

# depends_on:
#   - yarncache
# ---
# kind: pipeline
# type: exec
# name: macos

# platform:
#   os: darwin

# steps:
#   # - name: yarn
#   #   commands:
#   #     - export HOME=/Users/powerminion
#   #     - export HOMEPATH=/Users/powerminion
#   #     - yarn
#   - name: do the deed
#     commands:
#       - export HOME=/Users/powerminion
#       - export HOMEPATH=/Users/powerminion
#       - npx rnv export -p macos -s appstore -c selectorcanary --ci
# node:
#   runner: powerminion

# depends_on:
#   - yarncache
